```yaml
version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql666@
      MYSQL_DATABASE: collab_doc
    ports:
      - "3307:3307"

  redis:
    image: redis:7-alpine
    ports: 
      - "6379:6379"
